[package]
name = "larender"
version = "0.1.0"
authors = ["jac3k"]
edition = "2018"

[dependencies]
iup-sys = "0.0.3"
clear-coat = { git = "https://github.com/jminer/clear-coat" }
byteorder = "1.3.4"
zip = { version = "0.5.4", default-features = false, features = [ "deflate" ] }
image = "0.23.4"
glium = "0.27.0"
cgmath = "0.17.0"
